# Generated by Django 5.0.7 on 2025-03-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DairyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(max_length=1000)),
                ('mood', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('upload_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
    ]
